### PR TITLE
Create Account: Fix styling/code issues for Organisation dropdown #518

### PR DESCRIPTION
**Pull request by kmcgre**

### CODE REVIEW

**Comment by briri** [comment]
Just update the broken test and this will be good. It looks like maybe the accept_terms param needs to be updated to match what the form is sending back. The test is sending 'false' but the controller is doing a `!params[:accept_terms]` check.

```
  1) Failure:

RegistrationsControllerTest#test_user_receives_proper_error_messaging_if_they_have_not_accepted_terms [/home/travis/build/DMPRoadmap/roadmap/test/functional/registrations_controller_test.rb:26]:

--- expected

+++ actual

@@ -1 +1 @@

-"You must accept the terms and conditions to register."

+"Error processing registration. Please check that you have entered a valid email address and that your chosen password is at least 8 characters long."
```

**Comment by kmcgre** [comment]
I was looking at that but the form can't be submitted if the accept checkbox isn't checked so is this test needed?

**Comment by briri** [comment]
I think the test is beneficial. I'll fix on my end. Pulling this through and deploying so UAT can begin.

**Comment by vyruss** [comment]
@briri @kmcgre I'm in the process of turning it into a capybara test so we can test before submitting

**Pull request merged**
