### PR TITLE
Fix for issue #3161

### LINKED ISSUE #3161: Not catching data size too large.
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
v3.1

**Expected behaviour:**
Fill in Research Outputs tab, create a dataset, put in ridiculously large number for the size like 10,000,000 PB and it'll crash trying to save the integer. Shold give some sort of sensible error message

**Actual behaviour:**
Generic failure 500 message.

**Steps to reproduce:**
above

### PR DESCRIPTION
**Pull request by gjacob24**
Fixes #3161 

Changes proposed in this PR:
- Validation added in `research_output.rb` for when a user enters very large value as 'Anticipated file size'. The limit for validaiton is based on the max value for the byte_size column (bigint)

### CODE REVIEW

**Review by briri — APPROVED** [review]
Looks great @gjacob24 Thanks!

**Comment by gjacob24** [comment]
Added info about this PR to the Changelog 👍🏽

**Review by pengyin-shan — APPROVED** [review]
Looks good to me!

**Review by benjaminfaure — APPROVED** [review]
Looking good :)

**Pull request merged**
