### PR TITLE
Issue 1640

### LINKED ISSUE #1640: Option based questions have a limited number of options
Hello, 

You can't add more than 11 options in options based questions. 
Is it intended ? (It seems like an arbitrary number).

The limit can be removed in `lib/assets/javascripts/views/org_admin/question_options/index.js`
by replacing 
`const array = $(cloned).find('[id$="_number"]').prop('id').match(/_[\d]_+/);`
by
`const array = $(cloned).find('[id$="_number"]').prop('id').match(/_[\d]{1,2}_+/);` (the new limit would be 100 options)

### PR DESCRIPTION
**Pull request by benjaminfaure**
Fixes #1640 

(the `contributions` branch doesn't seem up to date at the moment)

### CODE REVIEW

**Comment by briri** [comment]
Yeah I'm not sure why it doesn't resolve them. I thought it retained the commit ids when you do that. I ended up pull the contributions branch down and doing a rebase to tidy up the history. I'll see if I can get it cleaned up.

**Comment by briri** [comment]
@xsrust to clean the commit history up I ended up pulling down the latest development. And then merging the OPIDoR changes into a new contributions branch and replacing this one. This was all performed locally:
- `git clone https://github.com/DMPRoadmap/roadmap.git core_roadmap`
- `cd core_roadmap`
- `git fetch origin development`
- `git checkout development`
- `git checkout -b contributions`
- `git checkout development`
- `git remote add opidor https://github.com/OPIDoR/DMPOPIDoR.git`
- `git fetch opidor issue_1640`
- `git checkout contributions`
- `git merge opidor/issue_1640`
- `git push -f origin contributions`

**Comment by stephaniesimms** [comment]
successfully removed the limit for option based questions. i noticed that we need to make the Text field accompanying the options mandatory, however, otherwise i can create an option-based question and publish it but no options are displayed in the UI. will create a separate issue for this.

**Comment by benjaminfaure** [comment]
@xsrust @briri next time I'll wait for the contributions branch to be synced with development if it's better for you :)

**Comment by briri** [comment]
@benjaminfaure the dev team discussed this issue in our call today and we are going to move away from the use of the contributions branch (I'll be updating the documentation shortly). Going forward you may submit any PRs directly to the development branch.

**Comment by benjaminfaure** [comment]
Thank you @briri  for the update !

**Pull request merged**
