### PR TITLE
Replace bin files with clean template versions

### LINKED ISSUE #1586: /Users/my-user-name/.rvm/rubies/ruby-2.4.4/bin/ruby: warning: shebang line ends with \r may cause a problem
**Expected behaviour:**
rails s should not give warning

**Actual behaviour:**
```
$ rails s
/Users/my-user-name/.rvm/rubies/ruby-2.4.4/bin/ruby: warning: shebang line ends with \r may cause a problem
```
**Steps to reproduce:**
Follow [wiki installation instructions](https://github.com/DMPRoadmap/roadmap/wiki/Installation)
Note: I use OSX, RVM, Ruby 2.4.4

### PR DESCRIPTION
**Pull request by Bodacious**
Fixes #1586.

Changes proposed in this PR:
- Fixes bug preventing bin executables from running on Mac OSX

Copied the bin files from a clean Rails 4.2.10 application.

### CODE REVIEW

**Comment by briri** [comment]
I'm not sure what problem this is solving. Is it specific to your environment? I'm developing on 2 separate Macs (iMac at the office and Macbook Pro at home) and have no trouble running `rails`, `rake` or `bundle`

**Comment by Bodacious** [comment]
@briri my preference is to run the app without Docker.

When I tried that on my own development machine (MacBook Pro running OSX 10.13) I wasn't able to run so much as a `rake -T` or any of the `rails ...` commands.

There was a warning displayed in the console when I tried—the same one that was raised by @Yu-Chieh-Henry-Yang in #1586:

`ruby: warning: shebang line ends with \r may cause a problem`

**Comment by briri** [comment]
Yeah I am getting the shebang error as well. The addition of these lines don't clear that error message up for me.
Are you able to run the bin executables now without these changes?

**Comment by Bodacious** [comment]
No, those executables won't run at all for me in their current form 😞

**Comment by briri** [comment]
ok. These changes shouldn't negatively impact anything so will accept the PR.

**Pull request merged**
