### PR TITLE
Rubocop - DO NOT MERGE YET

### PR DESCRIPTION
**Pull request by briri**
Fixes # .

Changes proposed in this PR:
-

### CODE REVIEW

**Comment by briri** [comment]
@raycarrick-ed please review and merge this one if everything looks ok. I had to adjust a few specs

**Comment by raycarrick-ed** [comment]
Spent an hour looking at this it's pretty hard to make sense of because of the changes to quotes which almost all of it. Will need a bit more time to get to grips with it.

**Comment by briri** [comment]
ok. I wonder if deploying it to a dev server and recruiting the product team to help QA would be useful. The tests are passing but the tests aren't exhaustive enough!

**Comment by raycarrick-ed** [comment]
I've deployed this to dmponline-test.dcc.ac.uk so patricia and magdalena can do some testing on it. So that hopefully we can get this merged in soon.

**Pull request merged**
