### PR TITLE
[don't merge] Refactor CSS assets to use Sprockets instead of Webpack

### LINKED ISSUE #1862: Refactor CSS assets for easier management
The CSS assets are not organised very neatly. We need to refactor these to make it easier to support custom branding.

- [x] Move CSS assets back to Rails's asset pipeline
- [x] Add support for LibC Sass (faster compilation)
- [x] Refactor CSS file structure for maintainability
- [ ] Normalise CSS variables

### PR DESCRIPTION
**Pull request by Bodacious**
Fixes #1862, #1762

Changes proposed in this PR:
- Move CSS files into `app/assets`
- Use Sprockets for SCSS compilation
- Update `rake assets:precompile` to support JS and CSS

### CODE REVIEW

**Comment by jollopre** [comment]
If I remember well, we decided to move towards npm to handle front-end related issues since they are more actively maintained than front-end assets handled through ruby gems.

Although these changes certainly keep the codebase more Rails focused, I got my doubts whether or not it is an appropriate move knowing that Rails 5 introduced Webpack on their assets pipeline...

**Comment by Bodacious** [comment]
Readme should be updated to include:

# Assets Management

## Javascripts

Javascript are written using ES6 and can be found in `app/assets/javascripts`. The application uses the recommended configuration for using Webpack in Rails 5: [the webpacker gem](https://github.com/rails/webpacker#installation).

You don't have to run a separate process for Webpack for JS to be compiled. This is compiled automatically on each request (in development).

Be sure to check the Rails log if you are seeing unexpected Javascript behaviour. There's an ESLint check run each time the assets are compiled, and errors are reported in the Rails log.

## Stylesheets, images and other assets

Stylesheets are written using Sassy CSS (via lib-c SASS)

Stylesheets use Rails' asset pipeline for compilation. For more information on how that is configured, please read this guide: https://guides.rubyonrails.org/asset_pipeline.html

## Compiling

To compile assets for development, please use the rake task `rake assets:precompile`

**Comment by briri** [comment]
👍 The changes look fine to me. I will need to do some updating of the customized CSS for the DMPTool once this is in place. 

It would be good to write up some recommendations/suggestions for how to go about customizing the CSS for local installations.

Feel free to merge into dev while I'm away

**Comment by xsrust** [comment]
@Bodacious as this is pointed at the next-sprint branch, is there still reason not to merge it into that branch?

**Comment by Bodacious** [comment]
@xsrust Let me have another look at it and make sure it's ready.

**Comment by Bodacious** [comment]
Please ignore this. Prefer #1962

**Comment by briri** [comment]
would suggest just closing this PR in favor of #1962

**Pull request closed without merging**
