### PR TITLE
Issue 677

### PR DESCRIPTION
**Pull request by jollopre**
- phases edit view and its sub-templates using local variables instead of instance variables. DMPRoadmap/roadmap#677
- conditional displaying of sub-templates at edit phase. This permits being re-used when previewing a template phase. DMPRoadmap/roadmap#677

### CODE REVIEW

**Comment by jollopre** [comment]
Note, the preview template functionality is now re-using the view phases/edit_plan_answers so that we don't have duplication of code anymore for displaying a phase

**Comment by briri** [comment]
The code looks fine but I had concerns that the JS behind the answer autosaving would still fire when in preview mode. I deployed this branch locally and noticed the following issues.
- I don't see a 'Preview' button to access the preview pages
- I also tested the Plan edit page and am getting a 'Couldn't find Answer' message during the answer autosave (see screenshot below). I'm guessing this has to do with the conversion of instance variables to locals

screen shot 2017-11-14 at 10 54 08 am

**Comment by jollopre** [comment]
@briri the template preview is accessed per phase, i.e. you have to select a phase and the preview button will be visible. It renders /phases/_edit_plan_answers.rb conditionally removing any HTML tag where a plan variable is needed.

Using instance variables in partials prevents re-using them unless the starting point, i.e. the controller action defines explicitly that variable. I would encourage all of us to avoid them if possible.

The JS that handles auto-saving is now aware of readonly mode and therefore does not add event handlers for forms (e.g. change, submit) neither does it for tinymce events (e.g. blur, focus). 

I have thoroughly tested both views (plan edit and template preview) and could not reproduce the screenshot you attached.

**Comment by briri** [comment]
resolved a couple of merge conflicts introduced by PR #832 
I kept everything from the issue677 branch with the exception of the `plan = eager_load2`. I used the line from the PR but switched it from instance variable `@plan` to `plan`

**Pull request merged**
