### PR TITLE
Fixed issue with number reordering for mysql data cleanup

### PR DESCRIPTION
**Pull request by briri**
addressed issues with mysql2 route for the question reordering function

### CODE REVIEW

**Comment by briri** [comment]
Not sure why this Postgres test keeps failing on the 'push' but not the 'pr'

**Comment by Bodacious** [comment]
@briri Can you explain what the issue was? I think we need to approach it from a different angle, as each of the number values needs to be updated in a single query. If not, then we risk having invalid data.

**Comment by briri** [comment]
There wasn't an error message or anything. It just turned out that after running the cleanup scripts that  I had more duplicate numbers than I started with (by a lot):
```shell
> bundle exec rake data_cleanup:find_known_invalidations
1893 Annotations with text is blank
0 Annotations with type is a duplicate
30 Answers with user is blank
705 Answers with question is a duplicate
1 ExportedPlans with plan is blank
0 Orgs with abbreviation is blank
5 Orgs with feedback_email_msg is blank
14 Orgs with feedback_email_subject is blank
11 Orgs with language is blank
1 Orgs with contact_email is invalid
1 Phases with duplicate_number is invalid
0 Plans with title is blank
9 Questions with number is duplicate
0 QuestionFormats with description is blank
1 Regions with description is blank
235 Roles with plan is blank
11 Sections with number is duplicate
52 Templates with locale is blank
0 UserIdentifiers with user is blank

> bundle exec rake data_cleanup:clean_invalid_records
Fix duplicate number on Phase
Fix blank plan on Role
Fix duplicate number on Section
Fix blank user on Answer
Fix duplicate question on Answer
Fix UserIdentifier records with no User
Fix name with leading or trailing space on Org
Fix blank language on Org
Fix invalid email on Org
Fix blank abbreviation on Org
Fix orgs where feedback_email_subject is blank
Fix orgs feedback_email_message is blank
Fix blank title on Plan
Fix blank plan on ExportedPlan
Fix blank locale on template
Fix blank text on Annotation
Fix duplicate type on Annotation
Fix duplicate number on Question
Fix blank description on QuestionFormat
Fix blank description on region

> bundle exec rake data_cleanup:find_known_invalidations
0 Annotations with text is blank
0 Annotations with type is a duplicate
0 Answers with user is blank
0 Answers with question is a duplicate
0 ExportedPlans with plan is blank
0 Orgs with abbreviation is blank
0 Orgs with feedback_email_msg is blank
0 Orgs with feedback_email_subject is blank
0 Orgs with language is blank
0 Orgs with contact_email is invalid
23 Phases with duplicate_number is invalid
0 Plans with title is blank
632 Questions with number is duplicate
0 QuestionFormats with description is blank
0 Regions with description is blank
0 Roles with plan is blank
495 Sections with number is duplicate
0 Templates with locale is blank
0 UserIdentifiers with user is blank
```

The proposed change here generates a hash of `{record_id: number}` and then updates each of those record ids individually so I'm not seeing where the risk lies. Its slower than a single query of course but wasn't too painful to run. .

**Comment by Bodacious** [comment]
@briri It's only really a risk if the loop is interrupted. If that happens, there might be duplicates.

It would be good to know more about those duplicate records you found. Technically, the SQL query should have caused that, unless there were duplicate IDs going into the method.

**Comment by briri** [comment]
Agreed. Will have to take a closer look at the records prior to the rake task and then again afterward.

**Comment by briri** [comment]
Going to close this one for now. Will rerun through the cleanup once I'm back from vacation.

**Pull request closed without merging**
