### PR TITLE
Issue #496 - Plan search issues.

### LINKED ISSUE #496: Add aria tags to modal dialogs
Make sure all modal dialogs are using the proper Aria tags.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role

Search for `modal` across the views to find the appropriate files. Also make sure that they follow the same pattern as the one found in the `views/layout/_signin_signout.html.erb`. 
This uses `data-toggle="modal"` attribute to signify that the link will open a modal and the `href` tag to indicate which div to display as the modal. That div should have the `class="modal"` attribute and a `style="display: none;"`

For example:
```html
<a href="#header-login-form" data-toggle="modal" dialog-width="450px"><%= _('Sign in')%></a> /
<a href="#header-register-form" data-toggle="modal" dialog-width="450px"><%= _('Create account')%></a>

<div id="header-login-form" class="modal" style="display:none">
  <%= render :partial => "shared/login_form" %>
</div>
<div id="header-register-form" class="modal" style="display:none">
  <%= render :partial => "shared/register_form", locals: {extended: false} %>
</div>
```

### PR DESCRIPTION
**Pull request by johnpinto1**
Fixes https://github.com/DigitalCurationCentre/DMPonline-Service/issues/496 (Digital Curation Centre issue)
Changes:
 - Replaced .where(Role.creator_condition) with .where(roles: { active: true })
 in model Plan search scope.

```
Note the API call for plans
/api/v0/plans?created_after=2019-11-01 gives an error:
"undefined method `grant_number' for #<Plan:0x00007fd5384ec108>\nDid you mean?  grant_id"
I think this is because changes made by @briri have not been merged???
```

### CODE REVIEW

**Comment by briri** [comment]
@johnpinto1 I think maybe this was corrected when I pulled in the latest from development. It shows zero files changed now

**Comment by johnpinto1** [comment]
@briri Locally my API call still  results in error after pulling merge above GET /api/v0/plans".  I thought I saw a fix by you for this error some time ago. 
{
  "source": "GET /api/v0/plans",
  "time": "2021-09-14T09:28:46+00:00",
  "code": 500,
  "message": "Internal Server Error",
  "total_items": 0,
  "items": [],
  "errors": [
    "undefined method `grant_number' for #<Plan:0x00007fdb0bdbef78>\nDid you mean?  grant_id"
  ]
}

**Comment by briri** [comment]
@johnpinto1 I do recall updating the view in `app/views/shared/export` but it seems to have been lost somehow.

Anyway, it looks like maybe its trying to reference `grant_number` in a few places. Can you update these as part of this PR when you have a chance?

Here's the output of a quick grep on the app directory:
```shell
briley@CDL-BRILEY-9M roadmap % grep -r 'grant_number' app 
app/models/exported_plan.rb:    plan.grant_number
app/models/concerns/exportable_plan.rb:    if grant_number.present?
app/models/concerns/exportable_plan.rb:      csv << [_("Grant number: "), _("%{grant_number}") % { grant_number: grant_number }]
app/javascript/src/plans/editDetails.js:              $('#grant_number_info').html(grantNumberInfo(grantId));
app/javascript/src/plans/editDetails.js:            $('#grant_number_info').html(grantNumberInfo(''));
app/views/plans/_project_details.html.erb:          <span class="text-muted" id="grant_number_info">Grant number: <%= plan.grant&.value %></span>
app/views/shared/export/_plan_txt.erb:  <% if @plan.grant_number.present? %>
app/views/shared/export/_plan_txt.erb:<%= _("Grant number: ") + @plan.grant_number %>
app/views/api/v0/statistics/plans.json.jbuilder:  json.grant_number   plan.grant_number
app/views/api/v0/plans/index.json.jbuilder:  json.grant_number   plan.grant_number
```

**Comment by johnpinto1** [comment]
Closing this PR as it is now relaced by https://github.com/DMPRoadmap/roadmap/pull/3034

**Pull request closed without merging**
