### PR TITLE
fix to properly use max per page settings

### PR DESCRIPTION
**Pull request by briri**
- Update API v1 to obey they `api_max_page_size` configuration param
- Update `paginable.rb` to use `results_per_page` instead of `api_max_page_size`

### CODE REVIEW

**Review by pengyin-shan — APPROVED** [review]
Tested your branch and it works. Thank you!

**Comment by johnpinto1** [comment]
@briri can I suggest you add logic to the Rest API version of V0  **app/controllers/api/v0/base_api_controller.rb**
as you have done for **app/controllers/api/v1/base_api_controller.rb** so that **Rails.configuration.x.application.api_max_page_size** value is taken into account in V0 too now that it has been removed from **app/controllers/concerns/paginable.rb**.

**Comment by johnpinto1** [comment]
@briri The API V1 works fine and UI pagination.

Found issue with API V0. It is broken. Trying to debug to get further info. Will add here.

**Comment by briri** [comment]
thanks @johnpinto1. I had originally added the function there to mimic v1 but then realized that plans was the only paginated endpoint and it needed `@args` instead of the individual `@per_page` and `@page`.

**Pull request merged**
