### PR TITLE
Issue 939

### PR DESCRIPTION
**Pull request by jollopre**
destroy action for themes. DMPRoadmap/roadmap#939

### CODE REVIEW

**Comment by briri** [comment]
Here's a screenshot of the issue referenced above
screen shot 2017-12-13 at 10 12 48 am

**Comment by jollopre** [comment]
I decided to remove lib/assets/javascripts/utils/linkHelper.js since this functionality is best handed through our third-party JS file (e.g. https://github.com/rails/jquery-ujs/blob/master/src/rails.js) part of vendor.js. 

The reason to this removal is because any link with data-remote attribute was augmented with a hidden form that was triggered anytime the link was clicked without taking into account confirmation dialogs (e.g. Cancel for cancelling the action, etc).

Moreover, as jquery-ujs, offers AJAX support out of the box by just annotating a form, button or link with remote: true. I have made changes in some files according to the custom events triggered by jquery-ujs to showcase how it works. Files changed:

- lib/assets/javascripts/views/plans/index.js
- lib/assets/javascripts/views/plans/share.js

To be consistent, we should adapt also the files but I think a new issue for that would be better. Below the remaining files to change:
- lib/assets/javascripts/views/answers/edit.js
- lib/assets/javascripts/views/notes/index.js
- lib/assets/javascripts/views/org_admin/templates/index.js
- lib/assets/javascripts/views/plans/new.js

**Comment by jollopre** [comment]
I attach here a link to the unobtrusive library that we have in place in case new work has to be added https://github.com/rails/jquery-ujs/wiki

**Comment by briri** [comment]
merging after discussion with @jollopre since this resolves the issue with the cancel button not working on confirmation messages. Will create a separate ticket to apply the changes to other ajax calls and make sure issues #870 and #933 are resolved.

**Pull request merged**
