### PR TITLE
 The "No. plans by template" statistics and visualisation changes:

### PR DESCRIPTION
**Pull request by johnpinto1**
(1) The headers for the CSV for the Number of Plans by Template
         - the date column have dates in the format  'Jan 2018'
         - the template headers now display the Title of the templates
         - the Date and Count headers are capitalized.

    (2) The chart has been re-styled.
        The aspect ratio (width/height) of image is now dynamically
        set according to the selection of the month range.

    (3) Fixed broken rspec tests.

    Fix for #1679.

Attached are files that show changes

LastMonth
3Months
6Months
9Months
12Months

We will need further tweaking of styling I am guessing.

The CSV file:  `Date,Standard CRUK Template,Hartstichting,AHRC Data Management Plan,Horizon 2020 DMP,LSE Data Management Plan for undergraduate and master's students dissertations,MRC Template,ESRC Template,LSE Data Management Plan for an undergraduate dissertation,LSE Bureau van Dijk Hard drive/Historical dataset access form,LSE Data Management Plan,ERC DMP,LSE Data Management Plan for taught master's students,Copy of LSE Data Management Plan for taught master's students,DCC Template,EPSRC Data Management Plan,Wellcome Trust Template,BBSRC Template,LSHTM DM Plan for research projects,NSF - generic,AHRC Template,NERC Template,Count
Feb 2019,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8
Jan 2019,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
Dec 2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Nov 2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Oct 2018,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6
Sep 2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Aug 2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jul 2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jun 2018,0,0,0,0,97,0,4,1,11,2,1,0,0,0,0,0,0,0,0,0,0,123
May 2018,0,0,0,3,42,0,7,0,4,13,0,11,24,0,0,0,0,0,0,0,0,104
Apr 2018,0,0,1,4,0,0,2,2,3,10,4,13,13,0,0,0,0,0,0,0,0,52
Mar 2018,0,0,0,3,0,0,6,0,4,15,1,57,2,1,1,1,0,0,0,0,0,93
Feb 2018,0,0,0,1,0,0,1,1,0,12,0,53,0,0,0,0,0,0,0,0,0,68
Jan 2018,0,0,0,1,0,0,1,3,1,22,1,40,0,0,0,0,0,0,0,0,0,69
Dec 2017,0,0,0,0,0,0,0,1,2,14,2,23,0,0,0,0,0,0,0,0,0,42
Nov 2017,0,0,0,3,0,0,8,4,3,24,0,19,0,0,0,0,1,0,0,0,0,62
Oct 2017,0,0,0,0,0,0,6,1,4,11,0,5,0,1,1,0,0,1,0,0,0,30
Sep 2017,0,0,0,0,0,0,0,0,0,12,0,7,0,0,0,0,0,0,1,0,0,20
Aug 2017,0,0,0,0,0,0,3,0,1,15,0,11,0,0,0,1,0,0,0,1,0,32
Jul 2017,0,0,0,0,0,0,2,0,1,11,0,8,0,0,0,0,0,0,0,0,0,22
Jun 2017,0,0,0,1,0,0,1,0,0,1,0,1,0,10,0,1,0,0,0,1,1,86
May 2017,0,0,0,0,0,0,1,0,0,1,0,1,0,6,0,1,0,0,0,1,0,44
Apr 2017,0,0,0,0,0,0,2,1,0,1,0,1,0,3,0,0,0,0,0,0,1,30
Mar 2017,0,0,0,3,0,0,4,1,1,1,0,1,0,13,0,0,0,0,0,1,0,78
Feb 2017,0,0,0,0,0,0,1,0,1,1,0,1,0,5,0,0,0,0,0,0,0,35
Jan 2017,0,0,0,0,0,0,2,0,1,1,0,1,0,1,0,0,0,0,0,0,0,29
Dec 2016,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,17
Nov 2016,0,0,0,2,0,0,3,1,1,1,0,1,0,2,0,0,0,0,0,0,0,31
Oct 2016,0,0,0,0,0,0,3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,4
Sep 2016,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,3
Aug 2016,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,5
Jul 2016,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,2
Jun 2016,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,4
May 2016,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,5
Apr 2016,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,6
Mar 2016,0,0,0,1,0,0,4,0,1,0,0,1,0,0,0,0,0,0,0,0,0,12
Feb 2016,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,3
Jan 2016,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,7
Dec 2015,0,0,0,2,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4
Nov 2015,0,0,0,0,0,0,8,1,0,0,0,1,0,0,0,0,0,0,0,0,0,11
Oct 2015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Sep 2015,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2
Aug 2015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jul 2015,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
Jun 2015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
May 2015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Apr 2015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Mar 2015,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
Feb 2015,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
Jan 2015,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
Dec 2014,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
Nov 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Oct 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Sep 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Aug 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jul 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jun 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
May 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Apr 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Mar 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Feb 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jan 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Dec 2013,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
Nov 2013,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Oct 2013,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Sep 2013,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0`

### CODE REVIEW

**Comment by briri** [comment]
hey @johnpinto1 Travis is notifying us that one of the Gem's needs to be updated due to a security issue. please go ahead and run `bundle update` on this feature branch and then push the change to update this PR

**Comment by johnpinto1** [comment]
@briri + @xsrust Updated gems. But found an issue with data being returned for display of Plan templates.  **So please don't merge yet.**

The data in Json format for the same year (but different time period choice) don't match. See images for Feb-19 above.  The **Time picker choice** for **Last Month** and **"3 Months"** for Feb-19 show 3 bars, but the number of bars increase for **Feb-19** if the choice is **6 Months**, **9 Months** and **12 Months** return different data for **Feb-19**.

**Comment by johnpinto1** [comment]
@briri & @xsrust Updated files that had rubocop warnings. Hopefully, all rests will pass now.

**Comment by johnpinto1** [comment]
@briri & @xsrust  I just fixed the outstanding JSLint issues that were breaking Travis builds.

**Comment by briri** [comment]
Yeah looks good @johnpinto1. Thanks for picking up the statistics work!

**Comment by johnpinto1** [comment]
@xsrust & @briri Fixed Gem.lock error by Travis.

**Pull request merged**
