### PR TITLE
Issue 1725 -  Fix for ensuring that Questions that are option based must have atleast one non-blank text entry.(DO NOT MERGE )

### PR DESCRIPTION
**Pull request by johnpinto1**
(DO NOT MERGE WITH CURRENT RELEASE CODE)
Fix for ensuring that Questions that are option based must have atleast one non-blank text entry.

Fix for #1725

Changes proposed in this PR:
- Validation added for option based questions to ensure text field non-blank.

### CODE REVIEW

**Comment by johnpinto1** [comment]
@briri Updated to add  validation message to app/models/concerns/validation_messages.rb as suggested.

**Comment by briri** [comment]
a forgot to mention that 'at least' should be 'at least' :)

**Comment by johnpinto1** [comment]
@briri Thanks for pointing out the typo 'atleast'. This has been corrected to 'at least'.

**Comment by briri** [comment]
Looks like you need to adjust some of the RSpec tests to work properly with these changes  @johnpinto1, otherwise the changes look fine to me.

**Comment by johnpinto1** [comment]
@briri @xsrust @Bodacious The fixing of tests will take longer than I expected. So will come back to this later.

**Comment by johnpinto1** [comment]
@briri @xsrust @Bodacious Closing this request. Need to rebase against development and fix tests. Will create a new PR when work done.

**Pull request closed without merging**
