### PR TITLE
New maDMP Research Outputs tab

### PR DESCRIPTION
**Pull request by briri**
**maDMP features**
- Added a new 'Research Outputs' tab to the edit Plan pages #2738 #2814
- Added a Metadata Standard selector to the Research Outputs page (allows user to select multiple standards) #2798 
- Added a License selector to the Research Outputs page #2607 
- Added a Repository selector to the Research Outputs page (allows user to select multiple repos) #2605
- Include Research Outputs as an appendix to the Plan's PDF #2812 Also includes a checkbox that allows the user to include/exclude it from the PDF
- Updated API V1 to convey the new Research Output info as Datasets in the JSON output
- Updated API V1 to extract some narrative elements from the Plan. It will find themed questions and build out a narrative (for example if there were 2 questions themed as "Preservation then it would set the `preservation_statement` in the JSON as: `"<p><strong>Question:</strong> What is your favorite color?<br><strong>Answer:</strong> blue</p><p><strong>Question:</strong> Why?<br><strong>Answer:</strong> Because I do!</p>"`). The theme to element mapping is:
  - The `data_quality_assurance` is populated from questions themed as "Data Collection"
  - The `preservation_statement` is populated from questions themed as "Preservation"
  - The `security_and_privacy` is populated from questions themed as "Ethics & privacy" and "Storage & security"
- Added config options that allow an installation to:
  - Disable/enable the Research Outputs tab entirely
  - Disable/enable the License selector
  - Disable/enable the Metadata Standard selector
  - Disable/enable the Repository selector
  - Disable/enable each of the individual narrative extractions (described in the bullet above)

**Other features/fixes**
- Added a new generic modal search dialog. This component allows the page to define its own search/filter options and display search results in its own way. (Included a README.md in the `app/views/layouts/modal_search` dir to help describe how to implement)
- Added a 'green' color to the CSS
- Modification to the way the Plan is associated with it's grant (basically a shortcut to get at the identifier record)
- Added new Services (and corresponding config files) to `services/external_apis` that fetch data for the License, Metadata Standard and Repository tables
- On the Plan PDFs I changed the title of the coversheet to "Plan Overview". When adding the new "Research Outputs" page I noticed that the coversheet and plan itself had the same names which makes it look odd in the PDF table of contents.
- Added a lot of tests

**DB changes**
- Added a 'licenses' table - populated via the SPDX API: `rails external_apis:load_spdx_licenses`
- Added a 'metadata_standards' table - populated via the RDA MSC API (hosted by Univ. of Bath): `rails external_apis:load_rdamsc_standards`
- Added a 'repositories' table - populated via the re3data API: `rails external_apis:load_re3data_repos`
-

### CODE REVIEW

**Comment by briri** [comment]
Hey @raycarrick-ed can you have a look at this Postgres error when you have a few minutes? I added some logic to switch between a Mysql and Postgres version of the Regex query but there seems to be something wrong with the Postgres version.

**Comment by briri** [comment]
finally passing! 😓

**Comment by briri** [comment]
FYI @benjaminfaure these changes may be of interest for your installation

**Comment by briri** [comment]
NOTE THAT THIS PR IS LIKELY OUT OF DATE WITH DMPTOOL

The DMPTool has had many updates since this PR was first created so an eval of these changes should be done to ensure that any bug fixes are included

**Comment by briri** [comment]
@raycarrick-ed this has been updated with all the latest from development and master. Will review with you all at our next dev meeting

**Comment by nicolasfranck** [comment]
method `process_grant` is removed from `PlansController`? Now the plan cannot be updated anymore from the detail page

**Comment by briri** [comment]
thanks for reviewing it @raycarrick-ed. I will merge then. The new research outputs tab is pretty self contained so teams can leave it disabled until they're ready.

**Comment by briri** [comment]
There is not at this time @nicolasfranck. The work done in the DMPTool was done in parallel with DMPOpidor's efforts. The table was based off of the original DMPOpidor table.

DMPOpidor's research outputs are tightly tied to a new way of building templates and storing them as JSON in the DB. The JSON contains both the content of the sections and questions but also the description of their structure (e.g. question A is a text area field). There is then logic that builds the page based on this JSON. @benjaminfaure can probably do a much more thorough job of explaining the difference 😄 

One of the nice things about the approach DMPOpidor took is that it is compatible with the current DMPRoadmap way of dealing with templates (they can be used in parallel.

**Pull request merged**
