### PR TITLE
DCC Bug 668 - Fix for issue of roles in a plan that does not have a

### PR DESCRIPTION
**Pull request by johnpinto1**
user_id set. This has proved in several cases.

Fix for DCC bug https://github.com/DigitalCurationCentre/DMPonline-Service/issues/688

Change in the Plan model method owner_and_coowners() we check that each
role we currently get has associated user that is not nil.

### CODE REVIEW

**Review by briri — APPROVED** [review]
looks good to me @johnpinto1 Thanks!

**Comment by raycarrick-ed** [comment]
Looks good to me too.
But the obvious question is: how do we end up with roles that have a nil user?

**Comment by johnpinto1** [comment]
@raycarrick-ed  I am guessing when you remove a owner or coowner or for matter any other role it removes the user_id from the Role but dies not de-link from the Plan. I need to check.
BTW if you are going to make an emergency patch for this, then I think you should also release patch for https://github.com/DMPRoadmap/roadmap/pull/3082 as they go together.

**I have not been able to replicate adding and removing Roles from a Plan.**

**Plan with no Shared users, just owner me:**
irb(main):001:0> **Plan.find(86949).roles**
 
=> #**<ActiveRecord::Associations::CollectionProxy [#<Role id: 124888, user_id: 33578, plan_id: 86949, created_at: "2021-10-25 09:12:38", updated_at: "2021-10-25 09:12:38", access: 15, active: true>]>**

  **After adding role (we have 2 roles)**
irb(main):003:0> **Plan.find(86949).roles**
  
=> #<ActiveRecord::Associations::CollectionProxy [#<Role id: 132334, user_id: 23749, plan_id: 86949, created_at: "2022-01-21 10:05:11", updated_at: "2022-01-21 10:05:11", access: 8, active: true>, #<Role id: 124888, user_id: 33578, plan_id: 86949, created_at: "2021-10-25 09:12:38", updated_at: "2021-10-25 09:12:38", access: 15, active: true>]>

**After removing user back to one role**
irb(main):005:0> **Plan.find(86949).roles**
  
=> #<ActiveRecord::Associations::CollectionProxy [#<Role id: 124888, user_id: 33578, plan_id: 86949, created_at: "2021-10-25 09:12:38", updated_at: "2021-10-25 09:12:38", access: 15, active: true>]>
----------------------------------------------------------------

**However,  is a Plan from Nottingham with a Role with user_id nil**
irb(main):013:0> **Plan.find(91948).roles**
 
=> #<ActiveRecord::Associations::CollectionProxy [#<Role id: 132294, user_id: 85683, plan_id: 91948, created_at: "2022-01-18 15:59:40", updated_at: "2022-01-18 15:59:40", access: 14, active: true>, #<Role id: 132300, **user_id: nil**, plan_id: 91948, created_at: "2022-01-18 16:30:09", updated_at: "2022-01-18 16:30:09", access: 14, active: true>, #<Role id: 132293, user_id: 85479, plan_id: 91948, created_at: "2022-01-18 15:59:19", updated_at: "2022-01-18 16:51:48", access: 15, active: false>]>

So I am unclear how this happened, as I have created users and removed them with no Roles lingering with user_id nil.

**Comment by johnpinto1** [comment]
Archiving user has popup

> You are about to archive s.h.banens@uu.nl.  This will remove their personal information, but retain their plans, answers, and comments.  They will be unable to sign-in. Are you sure?

This what happens on plan



Selection_007

**User id still there see second record**
irb(main):001:0> **Plan.find(86949).roles**
=> #<ActiveRecord::Associations::CollectionProxy [#<Role id: 132338, user_id: 86164, plan_id: 86949, created_at: "2022-01-21 10:49:37", updated_at: "2022-01-21 10:49:37", access: 14, active: true>, **#<Role id: 132337, user_id: 23749, plan_id: 86949, created_at: "2022-01-21 10:49:09", updated_at: "2022-01-21 10:49:30", access: 8, active: true>**, #<Role id: 124888, user_id: 33578, plan_id: 86949, created_at: "2021-10-25 09:12:38", updated_at: "2021-10-25 09:12:38", access: 15, active: true>]>

On removing from plan user the Role disappears.

Selection_008


irb(main):002:0> **Plan.find(86949).roles**
=> #<ActiveRecord::Associations::CollectionProxy [#<Role id: 132338, user_id: 86164, plan_id: 86949, created_at: "2022-01-21 10:49:37", updated_at: "2022-01-21 10:49:37", access: 14, active: true>, #<Role id: 124888, user_id: 33578, plan_id: 86949, created_at: "2021-10-25 09:12:38", updated_at: "2021-10-25 09:12:38", access: 15, active: true>]> 

So this scenario works as it should.

**Comment by johnpinto1** [comment]
So we are no closer to identifying how we ended up with Plans with roles that have user_id nil on our system.

**Comment by briri** [comment]
Hey @johnpinto1 and @raycarrick-ed. 

I just did a quick scan of the roles table in DMPTool and we have only 2 records with a nil user_id. One that was updated in September and the other in November of last year. Not sure what would be causing it though but I'm guessing it is an infrequent scenario. 

It may have something to do with the RolesController. In particular, [this block](https://github.com/DMPRoadmap/roadmap/blob/347b2fda7a2a5063642b2f211f03d5f2fd3eedef/app/controllers/roles_controller.rb#L51) where it attempts to 'invite' an unknown user. If invite isn't throwing an error (if the user entered email is perhaps invalid) then the fetch for the User record would return nil. The subsequent save of the Role would still occur because that model does not require a User association.

**Comment by johnpinto1** [comment]
@raycarrick-ed  & @briri Looks we too like CDL have only 2 Roles with nil users:

irb(main):004:0> **Role.where(user_id: nil).length**
**=> 2**
irb(main):005:0> **Role.where(user_id: nil)**
  <ActiveRecord::Relation [#<Role id: 130568, **user_id: nil**, plan_id: 73988, created_at: "2021-12-21 08:32:49", updated_at: "2021-12-21 08:32:49", access: 8, active: true>, 
#<Role id: 132300, **user_id: nil**, plan_id: 91948, created_at: "2022-01-18 16:30:09", updated_at: "2022-01-18 16:30:09", access: 14, active: true>]>
irb(main):006:0> 

One form **2021-12-21** and other more recently **2022-01-18**.

I think @briri has provided a plausible explanation for why this may have occurred.

**Pull request merged**
