### PR TITLE
Upgrade to Ruby v3.0

### LINKED ISSUE #3225: Upgrade Ruby to 3.0
We recently upgraded Ruby 2.6.3 to Ruby 2.7.6 during the upgrade to Rails 6.1.

We need to next migrate to Ruby 3.0. There are several language changes that will require intervention. In particular, the changes to positional and keyword arguments will need to be addressed. 

See: https://www.fastruby.io/blog/ruby/upgrades/upgrade-ruby-from-2.7-to-3.0.html

### PR DESCRIPTION
**Pull request by briri**
Fixes #3225 

- Upgrade to Ruby version 3.0.5
- Bumped all Github actions to use ruby 3.0
- Cleaned up Gemfile by: 
  - removing gems that were already commented out
  - removed `selenium-webdriver` and `capybara-webmock`
  - removing version restrictions on: `danger`, `font-awesome-sass`, `webdrivers`
- Ran into issue with `@import 'font-awesome-sprockets';` line in `app/assets/stylesheets/application.scss`. Removed that line after referring to the latest font-awesome install/setup guide which no longer includes it.
- Updated places that were incorrectly using keyword args. See [this article](https://makandracards.com/makandra/496481-changes-to-positional-and-keyword-args-in-ruby-3-0) for an overview
- Removed `.freeze` from Regex and Range constants since those types are already immutable
- Fixed Rubocop complaint about redundancy of `r.nil? ? nil : r.user`, so changed it to `r&.user` in `app/models/plan.rb`
- Fixed Rubocop complaint about redundant `::` in `config.log_formatter = ::Logger::Formatter.new` in `config/environments/production.rb`
- Froze deprecator constants that were Strings
- Cleaned up `spec/rails_helper.rb` and `spec/spec_helper.rb` 
- Simplified the `spec/support/capybara.rb` helper to work with the latest version of Capybara and use its built in headless Chrome driver

### CODE REVIEW

**Comment by briri** [comment]
@pengyin-shan I updated the Changelog but am not sure if I did it correctly though. I think the error above is with the Dangerfile itself

**Comment by briri** [comment]
I still need to work on the tests. I have them running locally, but GitHub actions don't seem to be happy.

**Comment by pengyin-shan** [comment]
> @pengyin-shan I updated the Changelog but am not sure if I did it correctly though. I think the error above is with the Dangerfile itself

Let me merge my previously fixed Danger PR...

**Comment by pengyin-shan** [comment]
> I still need to work on the tests. I have them running locally, but GitHub actions don't seem to be happy.

Is your local Danger not happy? It seems the Danger Github action is working fine

**Comment by pengyin-shan** [comment]
@briri for test related settings, this is currently what we have in Dangerfile:
```
has_test_changes = !git.modified_files.grep(/spec/).empty?

if git.lines_of_code > 50 && has_app_changes && !has_test_changes
  warn('There are code changes, but no corresponding tests. ' \
       'Please include tests if this PR introduces any modifications in ' \
       'behavior. \n
       Ignore this warning if the PR ONLY contains translation.io synced updates.',
       sticky: false)
end
```
Do you think we need to change/update anything?

**Comment by briri** [comment]
> Is your local Danger not happy? It seems the Danger Github action is working fine

My local Danger seems ok. The GitHub tests report an issue starting up Rails. They run fine in

**Pull request closed without merging**
