### PR TITLE
Issue #3144 - Upgrade to Bootstrap 5

### PR DESCRIPTION
**Pull request by gjacob24**
Following is a brief list of changes made by @johnpinto1 and @gjacob24 for the upgrade to Bootstrap 5. 
A more detailed version is in CHANGELOG.md (and in wiki: [https://github.com/DMPRoadmap/roadmap/wiki/Release-notes-for-Bootstrap-5-upgrade](https://github.com/DMPRoadmap/roadmap/wiki/Release-notes-for-Bootstrap-5-upgrade))

**Summary of changes:**
* Node package changes:
           - Changed version of bootstrap "^3.4.1" --> "^5.2.3"
           - Added @popperjs/core.
           - Removed bootstrap-3-typeahead, bootstrap-sass & popper.js

* Stylesheet changes:
          - In `app/assets/stylesheets/application.scss`:
            removed bootstrap-sass import and replaced with `@import "../../../node_modules/bootstrap/scss/bootstrap"`.
          - The order of the import statements have been changed to import the `blocks/` and `utils/` after the default bootstrap stylesheets
          - In `app/assets/stylesheets/blocks/`:
            replaced in relevant files `@use "../../../../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss" as * ;`
            with `@use "../../../../node_modules/bootstrap/scss/bootstrap" as *;`

* Bootstrap usage changes (look at CHANGELOG.mdorn wiki for details.). Many of these changes requires Javascripot changes too.
          - Bespoke versions replaced by Bootstrap 5 accordion and spinner.
          - Data attributes now use `-bs-` as required by Bootstrap 5 (used by accordion and dropdown buttons):
            `data-display` --> `data-bs-display`
            `data-parent` --> `data-bs-parent`
            `data-target` --> `data-bs-target`
            `data-toggle` --> `data-bs-toggle`
          - Bootstrap 5 Popover added to some dropdown-menu items by adding attribute `data-bs-toggle="popover"`.
          - Panels, thumbnails & wells have been dropped
          - Navs & navbars have been rewritten to follow changes in Bootsrap 5.
          - Notifications now use classes `d-block` and `d-none` to show and hide respectively.
          - The hidden and show classes have been removed because they conflicted with Jquery's. Replaced hidden with `d-none`.

### CODE REVIEW

**Comment by johnpinto1** [comment]
Rubocop fixes to follow soon.

**Comment by johnpinto1** [comment]
We found in the Template copy link. 
Selection_110

The modal first appears without link.
Selection_111

Onl second attempt modal appears with link.
Selection_112

**Comment by aaronskiba** [comment]
I tried merging the [Fix MySQL and PostgreSQL GitHub Actions PR](https://github.com/DMPRoadmap/roadmap/pull/3376) into this PR. There are a couple of noteworthy things after running the rspec tests:

1)

  ```ruby
  Failure/Error: expect(page).to have_text('0/1 answered')
  ```
  (Probably related to a change in `app/views/phases/_edit_plan_answers.html.erb`).

  `v4.1.1`
  Screenshot from 2024-03-12 13-39-54
  `Bootstrap PR`
  Screenshot from 2024-03-12 13-38-19

2)
```ruby
Failure/Error: expect(rendered.include?('modal-search-result-selector hidden')).to eql(true)
```
`v4.1.1` **Remove** option is displayed after adding a metadata standard
Screenshot from 2024-03-12 15-29-28
Screenshot from 2024-03-12 15-29-35

`Bootstrap PR` **Select** option is displayed after adding a metadata standard
Screenshot from 2024-03-12 15-32-13
Screenshot from 2024-03-12 15-32-23

**Comment by gjacob24** [comment]
Hi @aaronskiba thank you for spotting this. I am working on a fix for the second one and @johnpinto1 will look into the first one and we will hopefully sort it out soon.

**Comment by johnpinto1** [comment]
@aaronskiba I have partially fixed some of the Rspec tests. I have 6 tests still to fix. 

6 of these consistently fail although in exports-spec.rb the tests that fail vary with each run. locales_spec.rb on fails sometimes.

> Finished in 5 minutes 4 seconds (files took 2.4 seconds to load)
> 2088 examples, 7 failures, 5 pending
> 
> Failed examples:
> 
> rspec ./spec/features/locales_spec.rb:51 # Locales when new locale has no region user changes their locale
> rspec ./spec/features/modal_search_spec.rb:25 # ModalSearchDialog Modal search opens and closes and allows user to search, select and remove items
> rspec ./spec/features/templates/templates_upgrade_customisations_spec.rb:30 # Templates::UpgradeCustomisations Admin upgrades customizations from funder Template
> rspec ./spec/features/plans/exports_spec.rb:136 # PlansExports User downloads their plan as text
> rspec ./spec/features/plans/exports_spec.rb:37 # PlansExports User downloads public plan belonging to other User
> rspec ./spec/features/plans/exports_spec.rb:52 # PlansExports User downloads org plan belonging to User in same org
> rspec ./spec/features/annotations/annotations_editing_spec.rb:63 # Annotations::Editing Admin sets a Template's question annotation to blank string

**Comment by gjacob24** [comment]
Note: As part of the Rubocop fixes [commit](https://github.com/DMPRoadmap/roadmap/pull/3374/commits/6785bf3973e724a202f6907ade554f38204861cf) the default value for `dropdown` from file (app/views/paginable/templates/_customisable.html.erb) was removed. 
```
def link_to_customizable_template(name, customization, template, dropdown)
``` 



It is called in two places in the code and it is always called with a value for `dropdown`.
```
app/views/paginable/templates/_customisable.html.erb
18: <%= link_to_customizable_template "#{template.is_default ? '* ' : ''}#{template.title}", customization, template, false %>
54: <li><%= link_to_customizable_template "", customization, template, true %></li>
```

**Pull request merged**
