### PR TITLE
Bug 462 api not possible to get plan content

### LINKED ISSUE #462: Unpublished guidance is visible to users
Inist CNRS reported this issue and on investigation it seems to be correct. All individual pieces of guidance seem to be shown on front end regardless of whether it’s published or not.
guidance-publishing
guidance-publishing-2

Overall, the guidance group choice display seems to be pretty accurate. I did tests of adding groups and the main part this filtered out ones that were unpublished or didn’t have relevant pieces of guidance e.g. for themes not used in the template. 

I did a test though of unpublishing the Inist guidance group though. This didn’t remove it from the front end display, perhaps because the individual pieces of guidance are published? Logic would suggest that unpublishing the higher-level guidance group would override any individual pieces of guidance being published.

guidance-group-choices
guidance-group-choices-admin

### PR DESCRIPTION
**Pull request by johnpinto1**
Fixes #462:  Open API - not possible to get the content, plans throwing error

Changes proposed in this PR:
      - Reverted to replacing customised plans() method on Org model with
    the native plans() method.
    - Created a new org_admin_plans() method in Org model to replace old
    customised plans() for Org Admins. This picks up plans of users in Org
    that are co-owners of plans with plan.org_id of a different org.
    - Fixed a null pointer bug that broke the json output ig the Data contact was empty app/views/api/v0/plans/index.json.jbuilder.
    - Renamed method calls in case of Org Admins that used org.plans() to org.org_admin_plans().

### CODE REVIEW

**Comment by johnpinto1** [comment]
This is just to start conversation, as it will need critiquing.

**Review by raycarrick-ed — APPROVED** [review]
As far as I can see this looks ok. Adds in the plans that were missing and fixed the JSON failure. So looks good to me.

But test failure needs investigated a bit. Either test is wrong or new code: which is it?

**Comment by briri** [comment]
thanks for patching this @johnpinto1. Agree with Ray, just need to clean up those few tests. I'm guessing they may just need to be updated to use your new method instead of `org.plans`

**Comment by johnpinto1** [comment]
Fixing tests are proving trickier than expected. May take a day or two.

**Comment by johnpinto1** [comment]
@raycarrick @briri There change breaks these 3 tests in **org_rspec.rb** after changing subject to use **org_admin_plans()**. Incidentally, it fails with native **plans()** too. This is because the native **plans()** method plans are now added to **org_admin_plans()**. Advice required on how to proceed.

**Failed examples:**

rspec ./spec/models/org_spec.rb:405 # Org#plans user belongs to Org and plan user with role :commenter, but not :creator and :admin is expected not to include #<Plan id: 1, title: "utilize B2B vortals", template_id: 1, created_at: "2021-07-08 09:12:58", update...ant_id: nil, start_date: "2021-07-08 09:12:58", end_date: "2023-07-08 09:12:58", api_client_id: nil>
rspec ./spec/models/org_spec.rb:395 # Org#plans user belongs to Org and plan user with role :editor, but not :creator and :admin is expected not to include #<Plan id: 3, title: "synergize cross-platform markets", template_id: 3, created_at: "2021-07-08 09:1...ant_id: nil, start_date: "2021-07-08 09:12:58", end_date: "2023-07-08 09:12:58", api_client_id: nil>
rspec ./spec/models/org_spec.rb:415 # Org#plans user belongs to Org and plan user with role :reviewer, but not :creator and :admin is expected not to include #<Plan id: 4, title: "deliver enterprise e-commerce", template_id: 4, created_at: "2021-07-08 09:12:5...ant_id: nil, start_date: "2021-07-08 09:12:58", end_date: "2023-07-08 09:12:58", api_client_id: nil>

**Relevant tests:**
```
describe "#plans" do

    let!(:org) { create(:org) }
    let!(:plan) { create(:plan, org: org) }
    let!(:user) { create(:user, org: org) }

    subject { org.org_admin_plans }

....

context "user belongs to Org and plan user with role :editor, but not :creator and :admin" do

      before do
        plan.add_user!(user.id, :editor)
      end

      it { is_expected.not_to include(plan) }

    end

    context "user belongs to Org and plan user with role :commenter, but not :creator and :admin" do

      before do
        plan.add_user!(user.id, :commenter)
      end

      it { is_expected.not_to include(plan) }

    end

    context "user belongs to Org and plan user with role :reviewer, but not :creator and :admin" do

      before do
        plan.add_user!(user.id, :reviewer)
      end

      it { is_expected.not_to include(plan) }

    end

  end
```

**Comment by johnpinto1** [comment]
@raycarrick-ed @briri I fixed the tests. But I have a worry now all the tests for plans in **spec/models/org_spec.rb**
expect plans to be found. For these contexts:

- "when user belongs to Org and plan owner with role :creator"   **(Previously, did not include plan)** 
- "when user belongs to Org and plan user with role :administrator" 
- "user belongs to Org and plan user with role :editor, but not :creator and :admin" 
- "user belongs to Org and plan user with role :commenter, but not :creator and :admin" **(Previously, did not include plan)** 
- "user belongs to Org and plan user with role :reviewer, but not :creator and :admin"  **(Previously, did not include plan)**

**Comment by briri** [comment]
thanks @johnpinto1. I think its ok to update these tests to reflect the changes you have made. Those tests were written back in 2018.

**Comment by johnpinto1** [comment]
@briri Thanks for update. @raycarrick-ed  I believe this is now complete. So either merge.

**Pull request merged**
