### PR TITLE
Closes #390

### LINKED ISSUE #390: Profile page should display ORCID iD number
Previously the ORCID iD field displayed the number. Unless ORCID considers it best practice to state that "Your account has been linked..." I think we should keep the number here as that's also a field we want to auto-populate in the Plan details. Even though it's a long 16-digits that no one would memorize, users should get accustomed to seeing it written out next to the green ORCID logo. Ideally it should appear as a full URL (second screenshot)

screen shot 2017-06-01 at 2 17 58 pm

screen shot 2017-06-06 at 11 46 58 am

### PR DESCRIPTION
**Pull request by vyruss**
Fixed capitalization of ORCID

### CODE REVIEW

**Comment by briri** [comment]
This doesn't address the issue. The issue from #390 is that the link used to show the path to the user's ORCID page: http://orcid.org/0000-0001-9870-5882 with the orcid logo in front of the link (see the screenshot sample @stephaniesimms provided).

I had also originally implemented this to be more generic so that we didn't have to write specialized partials for each identifier scheme. I'd like to see us move back in that direction if possible. @bhavi added the logo and url for the landing page into the identifier schemes table. They are:
```
logo_url: http://orcid.org/sites/default/files/images/orcid_16x16.png
user_landing_url: https://orcid.org
```

**Comment by vyruss** [comment]
@briri it displayed the icon and link when I tested it. I also prefer the generic implementation but decided not to spend time unifying them again at this stage

**Comment by briri** [comment]
This is what we're seeing on roadmap-stg currently. Its based on this repo's CDL-MVP branch. 
screen shot 2017-07-25 at 8 09 42 am

**Comment by briri** [comment]
The label should be 'ORCID iD' and it should show the 'https://orcid.org/1234-1234-1234-1234' url.
It was also suggested that we stop using 'Shibboleth' and switch that to 'your organisation'

**Comment by stephaniesimms** [comment]
Users don't know what 'Shibboleth' is so I planned to create a separate issue to revise language about it throughout the tool. Here we should say: 'Your account has been linked to your institutional credentials'

**Comment by dsisu** [comment]
Are we talking about the same thing? The screen grab you sent doesn't match what I see on CDL-MVP.

**Comment by briri** [comment]
can you provide a screenshot @dsisu which server are you working with? roadmap-stg?

**Comment by briri** [comment]
closing this as it does not address the larger concerns with the orcid functionality. will readdress orcid tickets after bootstrap implementation

**Pull request closed without merging**
