### PR TITLE
Fix issue with downloads on the usage dashboard

### PR DESCRIPTION
**Pull request by briri**
Fixes https://github.com/DigitalCurationCentre/DMPonline-Service/issues/436

We changed around the organization of the Stat models and this one file was missed. We abstracted a bunch of redundant methods from the various StatX models and added them to an abstract Stat model which these now inherit from.

### CODE REVIEW

**Comment by magdalenadrafiova** [comment]
this threw the following message:

**Comment by magdalenadrafiova** [comment]
@magdalenadrafiova to retest and if fixed close

**Comment by magdalenadrafiova** [comment]
@briri @raycarrick still throws an error message :( 
I am using Mac > Google Chrome > and I logged in https://dmponline.manchester.ac.uk/ and https://dmponline.dcc.ac.uk/ and got the following message: 
Screenshot 2021-04-15 at 11 30 51
Screenshot 2021-04-15 at 11 29 15

**Comment by raycarrick-ed** [comment]
@pherterich @magdalenadrafiova 
once more - lets test and see if it's fixed. Should have been fixed as part of the restart tonight.

**Comment by magdalenadrafiova** [comment]
works thank you! closing :)

**Pull request merged**
